export const IMG_CDN_URL =
  'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/';

export const GET_RES_API =
  'https://www.swiggy.com/dapi/restaurants/list/v5?lat=12.9351929&lng=77.62448069999999&page_type=DESKTOP_WEB_LISTING"';

export const restaurantList = [
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '40476',
      name: 'Marathi Katta',
      uuid: '03bda414-f109-468e-beba-e1c9033cd3d7',
      city: '3',
      area: 'Rajamohallah',
      totalRatingsString: '',
      cloudinaryImageId: 'opgopiikpy3gvrmab9op',
      cuisines: ['Maharashtrian'],
      tags: [],
      costForTwo: 15000,
      costForTwoString: '₹150 FOR TWO',
      deliveryTime: 39,
      minDeliveryTime: 39,
      maxDeliveryTime: 39,
      slaString: '39 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'marathi-katta-koti-abids-koti',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Koti',
      parentId: 132544,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.6 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=40476',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        lastMileTravel: 0,
        lastMileDistance: 0.6,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.2',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '233052',
      name: 'Oven Story Pizza',
      uuid: '0ba769e9-b879-48b7-a8a5-de636af5f1ce',
      city: '3',
      area: 'Abids',
      totalRatingsString: '',
      cloudinaryImageId: 'ab979bffbd658e74de650a15ca0092a3',
      cuisines: ['Pizzas', 'Pastas', 'Italian', 'Desserts', 'Beverages'],
      tags: [],
      costForTwo: 40000,
      costForTwoString: '₹400 FOR TWO',
      deliveryTime: 29,
      minDeliveryTime: 24,
      maxDeliveryTime: 34,
      slaString: '24-34 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'ovenstory-pizza-abids-nampally',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Mahesh Nagar',
      parentId: 3534,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.9 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=233052',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 29,
        minDeliveryTime: 24,
        maxDeliveryTime: 34,
        lastMileTravel: 0,
        lastMileDistance: 1.9,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.7',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '2796',
      name: 'BlueFox',
      uuid: '4935a09a-f16b-4bdb-acaa-c3b8459075d9',
      city: '3',
      area: 'Himayatnagar',
      totalRatingsString: '',
      cloudinaryImageId: 'f4qom4lutrgkefkb5tmv',
      cuisines: ['Biryani', 'North Indian', 'Chinese', 'Tandoor'],
      tags: [],
      costForTwo: 80000,
      costForTwoString: '₹800 FOR TWO',
      deliveryTime: 78,
      minDeliveryTime: 78,
      maxDeliveryTime: 78,
      slaString: '78 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'blue-fox-himayath-nagar',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Himayath Nagar Road',
      parentId: 48033,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7495641~p=2~eid=00000189-880a-e77c-009e-880a008d024d~srvts=1690204563324~78798',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '2.9 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=2796',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 78,
        minDeliveryTime: 78,
        maxDeliveryTime: 78,
        lastMileTravel: 0,
        lastMileDistance: 2.9,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.2',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '495772',
      name: 'Cafe Niloufer',
      uuid: '9a064df4-fa62-4048-a4af-bf626c82dfee',
      city: '3',
      area: 'Himayath Nagar',
      totalRatingsString: '',
      cloudinaryImageId: 'e0c63e989612732c70da6d1bb6984850',
      cuisines: ['Bakery', 'Beverages', 'Snacks', 'Desserts'],
      tags: [],
      costForTwo: 40000,
      costForTwoString: '₹400 FOR TWO',
      deliveryTime: 70,
      minDeliveryTime: 70,
      maxDeliveryTime: 70,
      slaString: '70 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'café-niloufer-himayath-nagar-himayath-nagar',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Old Mla Quarters Road',
      parentId: 9152,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [
          {
            iconId: 'guiltfree/GF_Logo_android_3x',
            description: '',
            shortDescription: 'options available',
            fontColor: '#7E808C',
          },
        ],
      },
      lastMileTravelString: '1.8 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=495772',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 70,
        minDeliveryTime: 70,
        maxDeliveryTime: 70,
        lastMileTravel: 0,
        lastMileDistance: 1.8,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.5',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '355747',
      name: 'Grameen Kulfi',
      uuid: 'bc78eb9e-b256-413f-a60e-ec510f76fefb',
      city: '3',
      area: 'Narayanguda',
      totalRatingsString: '',
      cloudinaryImageId: 'mwggy9gmdboqzi7gloms',
      cuisines: ['Ice Cream', 'Desserts'],
      tags: [],
      costForTwo: 12000,
      costForTwoString: '₹120 FOR TWO',
      deliveryTime: 34,
      minDeliveryTime: 34,
      maxDeliveryTime: 34,
      slaString: '34 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'grameen-kulfi-kmit-himayath-nagar',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'KMIT',
      parentId: 12175,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 1500,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4400,
        message: '',
        title: 'Delivery Charge',
        amount: '4400',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'HEAVY',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.6 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=355747',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 34,
        minDeliveryTime: 34,
        maxDeliveryTime: 34,
        lastMileTravel: 0,
        lastMileDistance: 1.6,
        serviceability: 'SERVICEABLE',
        rainMode: 'HEAVY',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.6',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '624472',
      name: "Leon's - Burgers & Wings (Leon Grill)",
      uuid: 'abd90994-858e-455a-aaac-32d43469dcb7',
      city: '3',
      area: 'Himayat Nagar',
      totalRatingsString: '',
      cloudinaryImageId: 'jihaeqyqzda0eeno6viq',
      cuisines: ['American', 'Snacks', 'Turkish', 'Portuguese', 'Continental'],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 43,
      minDeliveryTime: 43,
      maxDeliveryTime: 43,
      slaString: '43 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant:
          "leon's---burgers-&-wings-(leon-grill)-himayath-nagar-himayath-nagar",
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'old Mla Quarters Road',
      parentId: 371281,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 1500,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4400,
        message: '',
        title: 'Delivery Charge',
        amount: '4400',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'HEAVY',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.9 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=624472',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 43,
        minDeliveryTime: 43,
        maxDeliveryTime: 43,
        lastMileTravel: 0,
        lastMileDistance: 1.9,
        serviceability: 'SERVICEABLE',
        rainMode: 'HEAVY',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.0',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '328570',
      name: 'Balaji dhaba',
      uuid: '3183b601-93b3-43cc-9fb6-9227bd0a3652',
      city: '3',
      area: 'Koti',
      totalRatingsString: '',
      cloudinaryImageId: 'c0ddd84c01f95220626ac14f45eafa65',
      cuisines: ['North Indian', 'Biryani', 'Chinese', 'Indian', 'Tandoor'],
      tags: [],
      costForTwo: 40000,
      costForTwoString: '₹400 FOR TWO',
      deliveryTime: 59,
      minDeliveryTime: 59,
      maxDeliveryTime: 59,
      slaString: '59 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'balaji-dhaba-himayath-nagar-himayath-nagar',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Himayath Nagar',
      parentId: 19043,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 1500,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4400,
        message: '',
        title: 'Delivery Charge',
        amount: '4400',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'HEAVY',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7238426~p=9~eid=00000189-881d-80b6-0093-6d1400fe097d~srvts=1690205782198~78798',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.1 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=328570',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 59,
        minDeliveryTime: 59,
        maxDeliveryTime: 59,
        lastMileTravel: 0,
        lastMileDistance: 1.1,
        serviceability: 'SERVICEABLE',
        rainMode: 'HEAVY',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '3.8',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '399267',
      name: 'Swiss Castle',
      uuid: '1d3a4caa-6c6d-4c95-96c3-7faded03378b',
      city: '3',
      area: 'Himayath Nagar',
      totalRatingsString: '',
      cloudinaryImageId: 'bt4dam1qz4x1sscimcgp',
      cuisines: ['Bakery', 'Sweets', 'Desserts'],
      tags: [],
      costForTwo: 50000,
      costForTwoString: '₹500 FOR TWO',
      deliveryTime: 32,
      minDeliveryTime: 32,
      maxDeliveryTime: 32,
      slaString: '32 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'swiss-castle-himayath-nagar-himayath-nagar',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Naryanguda Cross Road',
      parentId: 2532,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 1500,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4400,
        message: '',
        title: 'Delivery Charge',
        amount: '4400',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'HEAVY',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.9 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=399267',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        lastMileTravel: 0,
        lastMileDistance: 1.9,
        serviceability: 'SERVICEABLE',
        rainMode: 'HEAVY',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.5',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '637176',
      name: 'Naintara ( By Sri Narsingh Bhelpuri )',
      uuid: '5087b8ae-6670-4254-ba84-2160663bb00e',
      city: '3',
      area: 'Himayath Nagar',
      totalRatingsString: '',
      cloudinaryImageId: 'cjj7deoljlgra8oooyl9',
      cuisines: ['North Indian', 'Italian-American', 'Fast Food', 'Snacks'],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 42,
      minDeliveryTime: 42,
      maxDeliveryTime: 42,
      slaString: '42 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant:
          'naintara-(-by-sri-navtara-bhelpuri-)-himayath-nagar-himayath-nagar',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Boggul Kunta X Road',
      parentId: 379360,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.2 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=637176',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 42,
        minDeliveryTime: 42,
        maxDeliveryTime: 42,
        lastMileTravel: 0,
        lastMileDistance: 1.2,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.2',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '403007',
      name: "Haldiram's Sweets and Namkeen",
      uuid: '08a4d4d4-2093-4535-a7e5-21d59d6f26a3',
      city: '3',
      area: 'Himayath Nagar',
      totalRatingsString: '1000+ ratings',
      cloudinaryImageId: 'edf8410c87fc2a56e2e047bec146702b',
      cuisines: ['Sweets', 'Bakery', 'Desserts'],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 20,
      minDeliveryTime: 20,
      maxDeliveryTime: 20,
      slaString: '20 MINS',
      lastMileTravel: 1.399999976158142,
      slugs: {
        restaurant:
          'haldirams-sweets-and-namkeen-himayath-nagar-himayath-nagar',
        city: 'hyderabad',
      },
      cityState: '3',
      address:
        '5-2-1070/1-10, Shop no.2 to 4, Ground floor, Moti Mahal Market, Nizam Sahi Road, Abids, Hyderabad',
      locality: 'Ground floor, Moti Mahal Market',
      parentId: 391465,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.3 kms',
      hasSurge: false,
      sla: {
        restaurantId: '403007',
        deliveryTime: 20,
        minDeliveryTime: 20,
        maxDeliveryTime: 20,
        lastMileTravel: 1.399999976158142,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.2',
      totalRatings: 1000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '4138',
      name: 'Grand Hotel',
      uuid: 'c1a1d888-51b7-4bcc-b539-f884c796a015',
      city: '3',
      area: 'Koti',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'g1arzw6qd7g9affkmgzk',
      cuisines: ['Biryani', 'Chinese', 'Tandoor', 'Haleem'],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 22,
      minDeliveryTime: 22,
      maxDeliveryTime: 22,
      slaString: '22 MINS',
      lastMileTravel: 1.2000000476837158,
      slugs: {
        restaurant: 'grand-hotel-abids-himayath-nagar',
        city: 'hyderabad',
      },
      cityState: '3',
      address: 'Opposite Big Bazaar, 4-1-395,Abids Road, Hyderabad',
      locality: 'Abids Road',
      parentId: 4001,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7488565~p=4~eid=00000189-879c-0dcc-0030-ddc200f90433~srvts=1690197298636',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.2 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '10% OFF',
        subHeader: 'UPTO ₹40',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '4138',
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        lastMileTravel: 1.2000000476837158,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.1',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '233055',
      name: 'The Good Bowl',
      uuid: '5a848c50-ef8c-4fae-950a-6822062cc98d',
      city: '3',
      area: 'Abids',
      totalRatingsString: '',
      cloudinaryImageId: 'okstjh8yz2opj54g5rlq',
      cuisines: [
        'Biryani',
        'North Indian',
        'Pastas',
        'Punjabi',
        'Desserts',
        'Beverages',
      ],
      tags: [],
      costForTwo: 40000,
      costForTwoString: '₹400 FOR TWO',
      deliveryTime: 43,
      minDeliveryTime: 43,
      maxDeliveryTime: 43,
      slaString: '43 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'the-good-bowl-abids-nampally',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Mahesh Nagar',
      parentId: 7918,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.9 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=233055',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 43,
        minDeliveryTime: 43,
        maxDeliveryTime: 43,
        lastMileTravel: 0,
        lastMileDistance: 1.9,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.8',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '140117',
      name: 'Imperial Multi Cuisine Restaurant',
      uuid: '2fc26248-e811-4af0-8f7c-891d19f85440',
      city: '3',
      area: 'Malakpet',
      totalRatingsString: '',
      cloudinaryImageId: 'ib97mlmkhuwwv51syyca',
      cuisines: ['Biryani', 'Chinese', 'Indian', 'Kebabs', 'Tandoor'],
      tags: [],
      costForTwo: 40000,
      costForTwoString: '₹400 FOR TWO',
      deliveryTime: 63,
      minDeliveryTime: 63,
      maxDeliveryTime: 63,
      slaString: '63 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant:
          'imperial-multi-cuisine-restaurant-saroor-nagar-kothapet-dilsukhnagar',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'saidabad x road',
      parentId: 19253,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 4000,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4000,
        message: '',
        title: 'Delivery Charge',
        amount: '4000',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '3.6 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=140117',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 63,
        minDeliveryTime: 63,
        maxDeliveryTime: 63,
        lastMileTravel: 0,
        lastMileDistance: 3.6,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.1',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '17104',
      name: 'KFC',
      uuid: 'f08de782-23c6-4f4c-95f4-f26eeb368a5e',
      city: '3',
      area: 'Himayatnagar',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: '56c9ab92bd79745fd152a30fa2525426',
      cuisines: ['Burgers', 'Biryani', 'American', 'Snacks', 'Fast Food'],
      tags: [],
      costForTwo: 40000,
      costForTwoString: '₹400 FOR TWO',
      deliveryTime: 27,
      minDeliveryTime: 27,
      maxDeliveryTime: 27,
      slaString: '27 MINS',
      lastMileTravel: 2.5999999046325684,
      slugs: {
        restaurant: 'kfc-himayathnagar-himayath-nagar',
        city: 'hyderabad',
      },
      cityState: '3',
      address:
        'KFC Restaurant (Himayathnagar),The Brand Factory Building Plot No. 3-6-552 to 558/1 MPM Millennium, Wajhuddin Estate, Opp. Minerva, Advocates Colony, Himayath Nagar Hyderabad, Telangana 500029 India',
      locality: 'Prime Plaza',
      parentId: 547,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7354312~p=7~eid=00000189-879c-0dcc-0030-ddc300f90779~srvts=1690197298636',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '2.5 kms',
      hasSurge: false,
      sla: {
        restaurantId: '17104',
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        lastMileTravel: 2.5999999046325684,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.0',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '703934',
      name: 'Sagar Papaji Ka Dhaba ( Since 1985)',
      uuid: '0d436029-ae8f-41b1-bec0-8859750df49d',
      city: '3',
      area: 'Hanuman tekdi- Abids',
      totalRatingsString: '',
      cloudinaryImageId: 'f34657e4f398eec0e714971b58f8be69',
      cuisines: ['North Indian', 'Punjabi', 'Chinese', 'Beverages'],
      tags: [],
      costForTwo: 85000,
      costForTwoString: '₹850 FOR TWO',
      deliveryTime: 44,
      minDeliveryTime: 44,
      maxDeliveryTime: 44,
      slaString: '44 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'sagar-papaji-ka-dhaba-himayath-nagar-himayath-nagar',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Papaji Enclave',
      parentId: 174498,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.2 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=703934',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 44,
        minDeliveryTime: 44,
        maxDeliveryTime: 44,
        lastMileTravel: 0,
        lastMileDistance: 1.2,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.2',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '547809',
      name: 'Theobroma',
      uuid: 'e6303a6e-b41d-4041-8f9c-dde9d3986000',
      city: '3',
      area: 'Himayath Nagar',
      totalRatingsString: '1000+ ratings',
      cloudinaryImageId: 'wxr6gobr4fbwrp3j91dt',
      cuisines: ['Desserts'],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 28,
      minDeliveryTime: 28,
      maxDeliveryTime: 28,
      slaString: '28 MINS',
      lastMileTravel: 3,
      slugs: {
        restaurant: 'theobroma-himayath-nagar-himayath-nagar',
        city: 'hyderabad',
      },
      cityState: '3',
      address:
        '3-6-138/5 & 6, GROUND FLOOR, PAPALAL CHAMBERS, HIMAYATNAGAR Circle, Hyderabad, Telangana   500029',
      locality: 'Papalal Chambers',
      parentId: 1040,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 3500,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 3500,
        message: '',
        title: 'Delivery Charge',
        amount: '3500',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7564807~p=10~eid=00000189-879c-0dcc-0030-ddc400f90a73~srvts=1690197298636',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '3 kms',
      hasSurge: false,
      sla: {
        restaurantId: '547809',
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        lastMileTravel: 3,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.4',
      totalRatings: 1000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '8593',
      name: 'Sri Radhe Chills and Thrills',
      uuid: 'b9430e8e-e356-45f8-893f-4a3f15771930',
      city: '3',
      area: 'Koti',
      totalRatingsString: '',
      cloudinaryImageId: 'ecpdpkch1c1ljqfuquxo',
      cuisines: ['Italian', 'Juices'],
      tags: [],
      costForTwo: 20000,
      costForTwoString: '₹200 FOR TWO',
      deliveryTime: 56,
      minDeliveryTime: 56,
      maxDeliveryTime: 56,
      slaString: '56 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant:
          'sri-radhe-chills-and-thrills-bogulakunta-cross-road-abids-koti',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Abids',
      parentId: 19628,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.2 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=8593',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 56,
        minDeliveryTime: 56,
        maxDeliveryTime: 56,
        lastMileTravel: 0,
        lastMileDistance: 1.2,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.2',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '142670',
      name: 'Shah Ghouse Cafe & Restaurant',
      uuid: '88b357e6-6560-449b-9400-5e9a9915db66',
      city: '3',
      area: 'Lakdikapul',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'bk26jkkqpg55veii0aj9',
      cuisines: ['Biryani', 'Chinese', 'Tandoor', 'Mughlai', 'North Indian'],
      tags: [],
      costForTwo: 35000,
      costForTwoString: '₹350 FOR TWO',
      deliveryTime: 42,
      minDeliveryTime: 42,
      maxDeliveryTime: 42,
      slaString: '42 MINS',
      lastMileTravel: 4.199999809265137,
      slugs: {
        restaurant: 'shah-ghouse-cafe-restaurant-lakdikapool-nampally',
        city: 'hyderabad',
      },
      cityState: '3',
      address: '6-2-971,Lakdikapool,Hyd',
      locality: 'Santh Nirankari Satsang Bhavan',
      parentId: 18992,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 4100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4100,
        message: '',
        title: 'Delivery Charge',
        amount: '4100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7364358~p=13~eid=00000189-879c-0dcc-0030-ddc500f90d13~srvts=1690197298636',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '4.1 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '30% OFF',
        subHeader: 'UPTO ₹75',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '142670',
        deliveryTime: 42,
        minDeliveryTime: 42,
        maxDeliveryTime: 42,
        lastMileTravel: 4.199999809265137,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.1',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '46287',
      name: 'Balaji Santosh Dhaba',
      uuid: '8a1dc49c-147b-4b81-9eaa-39ae2707ea00',
      city: '3',
      area: 'Kachiguda',
      totalRatingsString: '',
      cloudinaryImageId: 'arnwipcwjgjyqofehjtg',
      cuisines: ['North Indian', 'Biryani', 'Chinese'],
      tags: [],
      costForTwo: 35000,
      costForTwoString: '₹350 FOR TWO',
      deliveryTime: 37,
      minDeliveryTime: 37,
      maxDeliveryTime: 37,
      slaString: '37 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'santosh-plus-family-dhaba-kacheguda-kachiguda',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Kachiguda Station Rd',
      parentId: 5225,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=46287',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        lastMileTravel: 0,
        lastMileDistance: 1,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.1',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '700497',
      name: 'Pista House Restaurant & Bakery',
      uuid: 'be06298d-08f8-4cd9-b087-20f3df79718b',
      city: '3',
      area: 'Gaddiannaram',
      totalRatingsString: '1000+ ratings',
      cloudinaryImageId: '8897124781976e694d84046bd90f7270',
      cuisines: [
        'Biryani',
        'North Indian',
        'Chinese',
        'Kebabs',
        'Tandoor',
        'Desserts',
      ],
      tags: [],
      costForTwo: 50000,
      costForTwoString: '₹500 FOR TWO',
      deliveryTime: 26,
      minDeliveryTime: 26,
      maxDeliveryTime: 26,
      slaString: '26 MINS',
      lastMileTravel: 4.599999904632568,
      slugs: {
        restaurant: 'pista-house-restaurant-&-bakery-madhapur-madhapur',
        city: 'hyderabad',
      },
      cityState: '3',
      address:
        '16-11-729, Dilsukhnagar, Gaddiannaram, Malakpet Circle No 6, Hyderabad, Telangana',
      locality: 'Dilsukhnagar',
      parentId: 319765,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 4100,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4100,
        message: '',
        title: 'Delivery Charge',
        amount: '4100',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '4.5 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '50% OFF',
        subHeader: 'UPTO ₹100',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '700497',
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        lastMileTravel: 4.599999904632568,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.1',
      totalRatings: 1000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '10882',
      name: 'Madhur Sweets',
      uuid: '241920ad-fe43-46a9-9307-31cf4b4cbab3',
      city: '3',
      area: 'Masab Tank',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'y8iljdwvxte9e7rarib7',
      cuisines: ['Sweets', 'Desserts', 'Snacks'],
      tags: [],
      costForTwo: 25000,
      costForTwoString: '₹250 FOR TWO',
      deliveryTime: 42,
      minDeliveryTime: 42,
      maxDeliveryTime: 42,
      slaString: '42 MINS',
      lastMileTravel: 5.699999809265137,
      slugs: {
        restaurant: 'madhur-sweets-humayun-nagar-mehdipatnam',
        city: 'hyderabad',
      },
      cityState: '3',
      address: '10-3-310/B1& 2,Near NMDC,Humayun Nagar,Mehdipatnam',
      locality: 'Humayun Nagar',
      parentId: 1538,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 5400,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 5400,
        message: '',
        title: 'Delivery Charge',
        amount: '5400',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7498236~p=16~eid=00000189-879c-0dcc-0030-ddc600f91042~srvts=1690197298636',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '5.6 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '10% OFF',
        subHeader: 'UPTO ₹40',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '10882',
        deliveryTime: 42,
        minDeliveryTime: 42,
        maxDeliveryTime: 42,
        lastMileTravel: 5.699999809265137,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.5',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '32129',
      name: 'Burger King',
      uuid: '137eda4d-6758-4002-aa35-c46130fde14b',
      city: '3',
      area: 'Himayatnagar',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'e33e1d3ba7d6b2bb0d45e1001b731fcf',
      cuisines: ['Burgers', 'American'],
      tags: [],
      costForTwo: 35000,
      costForTwoString: '₹350 FOR TWO',
      deliveryTime: 35,
      minDeliveryTime: 35,
      maxDeliveryTime: 35,
      slaString: '35 MINS',
      lastMileTravel: 2.5999999046325684,
      slugs: {
        restaurant: 'burger-king-mpm-millennium-mall-himayath-nagar',
        city: 'hyderabad',
      },
      cityState: '3',
      address:
        'Burger King India Pvt Ltd, Unit No. 104 A, 105 A, 106 & 107, MPM Millennium Mall, GHMC Nos. 3-6-552 to 3-6-558 & 558/1, Himayatnagar Main Road, Himayatnagar, Hyderabad - 500029',
      locality: 'MPM Millennium Mall',
      parentId: 166,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '2.5 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: 'FREE ITEM',
        subHeader: '',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '32129',
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        lastMileTravel: 2.5999999046325684,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.1',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '721101',
      name: 'Pista House Bakery',
      uuid: '93a900b2-7943-4868-bcb5-44ca9649a5cf',
      city: '3',
      area: 'Abids & Koti',
      totalRatingsString: 'Too Few Ratings',
      cloudinaryImageId: '6a02cee5c367c438ec8a4becf0b98b1c',
      cuisines: ['Indian', 'Bakery'],
      tags: [],
      costForTwo: 50000,
      costForTwoString: '₹500 FOR TWO',
      deliveryTime: 35,
      minDeliveryTime: 35,
      maxDeliveryTime: 35,
      slaString: '35 MINS',
      lastMileTravel: 1.2000000476837158,
      slugs: {
        restaurant: 'pista-house-bakery-abids-&-koti-abids-&-koti',
        city: 'hyderabad',
      },
      cityState: '3',
      address:
        'Door No. 3-5-142/2 to 4, King Kothi, kothi, Hyderabad-T.S, Goshamahal Circle No. 14, Hyderabad, Telangana',
      locality: 'King Koth',
      parentId: 19008,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 2900,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.2 kms',
      hasSurge: false,
      sla: {
        restaurantId: '721101',
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        lastMileTravel: 1.2000000476837158,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '--',
      totalRatings: 0,
      new: true,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '450654',
      name: 'Pista House Bakery',
      uuid: '53152e53-a64f-463a-8929-e2f7972d8605',
      city: '3',
      area: 'Charminar',
      totalRatingsString: '',
      cloudinaryImageId: 'suoms7x4ptt84oeqvl6y',
      cuisines: ['Continental', 'Pizzas', 'Snacks'],
      tags: [],
      costForTwo: 20000,
      costForTwoString: '₹200 FOR TWO',
      deliveryTime: 77,
      minDeliveryTime: 77,
      maxDeliveryTime: 77,
      slaString: '77 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'pista-house-bakery-kotla-charminar-charminar',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Alijah Kotla',
      parentId: 19008,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 3500,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 3500,
        message: '',
        title: 'Delivery Charge',
        amount: '3500',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '3.6 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=450654&source=collection&query=Burger',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 77,
        minDeliveryTime: 77,
        maxDeliveryTime: 77,
        lastMileTravel: 0,
        lastMileDistance: 3.6,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.2',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '627630',
      name: 'The Wrap House\t',
      uuid: '31396a0a-cfc6-4d21-9795-92ba31263f58',
      city: '3',
      area: 'Charminar',
      totalRatingsString: '',
      cloudinaryImageId: 'svcvdjdzviljlzmssc3x',
      cuisines: ['Fast Food', 'Salads', 'Snacks'],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 63,
      minDeliveryTime: 63,
      maxDeliveryTime: 63,
      slaString: '63 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'the-wrap-house-charminar-charminar-2',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Malakpet Circle No 6',
      parentId: 215452,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.4 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=627630&source=collection&query=Burger',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 63,
        minDeliveryTime: 63,
        maxDeliveryTime: 63,
        lastMileTravel: 0,
        lastMileDistance: 1.4,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.2',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '163382',
      name: 'New Deccan Bakers and Sweet Shop',
      uuid: '423c7114-7472-413d-a12f-0bca3dfbe711',
      city: '3',
      area: 'Tad Bun',
      totalRatingsString: '',
      cloudinaryImageId: 'cjamwa0jqcfo4i8z3pbt',
      cuisines: ['Sweets', 'North Indian', 'Bakery'],
      tags: [],
      costForTwo: 10000,
      costForTwoString: '₹100 FOR TWO',
      deliveryTime: 80,
      minDeliveryTime: 80,
      maxDeliveryTime: 80,
      slaString: '80 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'new-deccan-bakers-and-sweet-shop-charminar',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'mecca colony kalapather',
      parentId: 146314,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 6600,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 6600,
        message: '',
        title: 'Delivery Charge',
        amount: '6600',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '7.6 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=163382&source=collection&query=Burger',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 80,
        minDeliveryTime: 80,
        maxDeliveryTime: 80,
        lastMileTravel: 0,
        lastMileDistance: 7.6,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.8',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '6994',
      name: 'Santosh Dhaba Exclusive',
      uuid: 'e581eb1b-746e-4b02-a31e-ccd03f835b9b',
      city: '3',
      area: 'Koti',
      totalRatingsString: '',
      cloudinaryImageId: 'jllcesio37olflwnvter',
      cuisines: [
        'North Indian',
        'Biryani',
        'Chinese',
        'Italian',
        'Mexican',
        'Desserts',
      ],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 65,
      minDeliveryTime: 65,
      maxDeliveryTime: 65,
      slaString: '65 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'santosh-dhaba-exclusive-hanuman-tekdi-abids-koti',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Hanuman Tekdi',
      parentId: 8784,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7364268~p=3~eid=00000189-880a-e77c-009e-880b008d0352~srvts=1690204563324~78798',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.1 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=6994',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 65,
        minDeliveryTime: 65,
        maxDeliveryTime: 65,
        lastMileTravel: 0,
        lastMileDistance: 1.1,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.0',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '483586',
      name: 'Kwality Walls Frozen Dessert and Ice Cream Shop',
      uuid: 'd59f77f8-a870-41b4-95fd-777ecae471bc',
      city: '3',
      area: 'Kothapet & Dilsukhnagar',
      totalRatingsString: '',
      cloudinaryImageId: 'zu4d0mxfsxdmvohabr1e',
      cuisines: ['Desserts', 'Ice Cream', 'Ice Cream Cakes'],
      tags: [],
      costForTwo: 20000,
      costForTwoString: '₹200 FOR TWO',
      deliveryTime: 50,
      minDeliveryTime: 50,
      maxDeliveryTime: 50,
      slaString: '50 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant:
          'kwality-wall’s-frozen-dessert-&-ice-cream-shop-kothapet-&-dilsukhnagar-kothapet-&-dilsukhnagar-2',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Circle No 6',
      parentId: 582,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 1500,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4400,
        message: '',
        title: 'Delivery Charge',
        amount: '4400',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'HEAVY',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.9 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=483586',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 50,
        minDeliveryTime: 50,
        maxDeliveryTime: 50,
        lastMileTravel: 0,
        lastMileDistance: 1.9,
        serviceability: 'SERVICEABLE',
        rainMode: 'HEAVY',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.4',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '31970',
      name: 'Mandilicious',
      uuid: 'd1eac715-64fc-4255-8d0c-98aa5a758298',
      city: '3',
      area: 'Himayatnagar',
      totalRatingsString: '',
      cloudinaryImageId: 'mlgfiq55ub5xz910s7rp',
      cuisines: ['Arabian', 'Indian', 'Chinese'],
      tags: [],
      costForTwo: 45000,
      costForTwoString: '₹450 FOR TWO',
      deliveryTime: 75,
      minDeliveryTime: 75,
      maxDeliveryTime: 75,
      slaString: '75 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'mandilicious-himayathnagar-himayath-nagar',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Himayath Nagar',
      parentId: 131565,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7246099~p=4~eid=00000189-880a-e77c-009e-880c008d043c~srvts=1690204563324~78798',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '2.8 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=31970',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 75,
        minDeliveryTime: 75,
        maxDeliveryTime: 75,
        lastMileTravel: 0,
        lastMileDistance: 2.8,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '3.9',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '523794',
      name: 'Capital Multicuisine Restaurant',
      uuid: '69beb71d-97b8-410b-bcf6-25193b8b0b92',
      city: '3',
      area: 'Himayath Nagar',
      totalRatingsString: '',
      cloudinaryImageId: 'rkbt9oto4ub6d4uhmu35',
      cuisines: ['Biryani', 'Arabian', 'Lebanese'],
      tags: [],
      costForTwo: 35000,
      costForTwoString: '₹350 FOR TWO',
      deliveryTime: 63,
      minDeliveryTime: 63,
      maxDeliveryTime: 63,
      slaString: '63 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant:
          'capital-multicuisine-restaurant-himayath-nagar-himayath-nagar',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Himayath Nagar',
      parentId: 19262,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '2.1 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=523794',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 63,
        minDeliveryTime: 63,
        maxDeliveryTime: 63,
        lastMileTravel: 0,
        lastMileDistance: 2.1,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.7',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '8593',
      name: 'Sri Radhe Chills and Thrills',
      uuid: 'b9430e8e-e356-45f8-893f-4a3f15771930',
      city: '3',
      area: 'Koti',
      totalRatingsString: '',
      cloudinaryImageId: 'ecpdpkch1c1ljqfuquxo',
      cuisines: ['Italian', 'Juices'],
      tags: [],
      costForTwo: 20000,
      costForTwoString: '₹200 FOR TWO',
      deliveryTime: 76,
      minDeliveryTime: 76,
      maxDeliveryTime: 76,
      slaString: '76 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant:
          'sri-radhe-chills-and-thrills-bogulakunta-cross-road-abids-koti',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Abids',
      parentId: 19628,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7239034~p=5~eid=00000189-880a-e77c-009e-880d008d0532~srvts=1690204563324~78798',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.2 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=8593',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 76,
        minDeliveryTime: 76,
        maxDeliveryTime: 76,
        lastMileTravel: 0,
        lastMileDistance: 1.2,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.2',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '6851',
      name: 'Agrawala Sweets',
      uuid: '0a169124-b7d8-491d-8355-76a50b1c65f5',
      city: '3',
      area: 'Abids',
      totalRatingsString: '',
      cloudinaryImageId: 'ucxry3ehtkkpadyzsyrq',
      cuisines: ['Sweets'],
      tags: [],
      costForTwo: 25000,
      costForTwoString: '₹250 FOR TWO',
      deliveryTime: 67,
      minDeliveryTime: 67,
      maxDeliveryTime: 67,
      slaString: '67 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'agrawala-jn-road-abids-koti',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'JN Road',
      parentId: 27894,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.5 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=6851',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 67,
        minDeliveryTime: 67,
        maxDeliveryTime: 67,
        lastMileTravel: 0,
        lastMileDistance: 1.5,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.3',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '624526',
      name: "La Pino'z Pizza",
      uuid: '68beed3e-6133-4119-b91d-9b0e967dbc46',
      city: '3',
      area: 'Liberty Road',
      totalRatingsString: '',
      cloudinaryImageId: 'eydflhsjdfaqktybte8n',
      cuisines: ['Pizzas', 'Pastas', 'Italian', 'Desserts', 'Beverages'],
      tags: [],
      costForTwo: 40000,
      costForTwoString: '₹400 FOR TWO',
      deliveryTime: 78,
      minDeliveryTime: 78,
      maxDeliveryTime: 78,
      slaString: '78 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'la-pinoz-pizza-liberty-road-himayath-nagar',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Himayath Nagar',
      parentId: 4961,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: '',
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: '',
        headerType: 0,
        superFreedel: '',
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 3500,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 3500,
        message: '',
        title: 'Delivery Charge',
        amount: '3500',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7213339~p=6~eid=00000189-880a-e77c-009e-880e008d060b~srvts=1690204563324~78798',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '3 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=624526',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 78,
        minDeliveryTime: 78,
        maxDeliveryTime: 78,
        lastMileTravel: 0,
        lastMileDistance: 3,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '3.9',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '6927',
      name: 'Bombay Juice',
      uuid: 'a4dfebc5-8ec4-41b7-b63f-393a21ba7ae4',
      city: '3',
      area: 'Koti',
      totalRatingsString: '',
      cloudinaryImageId: 'fngjhkvws1o6ehegeyrv',
      cuisines: ['Chaat', 'Chinese', 'Juices'],
      tags: [],
      costForTwo: 20000,
      costForTwoString: '₹200 FOR TWO',
      deliveryTime: 66,
      minDeliveryTime: 66,
      maxDeliveryTime: 66,
      slaString: '66 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'bombay-juice-sultan-bazar-abids-koti',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Sultan Bazar',
      parentId: 3843,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [
          {
            iconId: 'guiltfree/GF_Logo_android_3x',
            description: '',
            shortDescription: 'options available',
            fontColor: '#7E808C',
          },
        ],
      },
      lastMileTravelString: '1 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=6927',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 66,
        minDeliveryTime: 66,
        maxDeliveryTime: 66,
        lastMileTravel: 0,
        lastMileDistance: 1,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.3',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '131927',
      name: 'New Agra Sweets',
      uuid: 'ad977046-495c-4cc3-99e2-cd270591723e',
      city: '3',
      area: 'Feelkhana',
      totalRatingsString: '',
      cloudinaryImageId: 'kwgwtcvvkajdvksvtkan',
      cuisines: ['Sweets', 'Desserts'],
      tags: [],
      costForTwo: 15000,
      costForTwoString: '₹150 FOR TWO',
      deliveryTime: 57,
      minDeliveryTime: 57,
      maxDeliveryTime: 57,
      slaString: '57 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'new-agra-sweets-begum-bazaar-nampally',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'Siddiamberbazar Feelkhana',
      parentId: 145695,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 1500,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4400,
        message: '',
        title: 'Delivery Charge',
        amount: '4400',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7516407~p=11~eid=00000189-880a-e77c-009e-8813008d0b1f~srvts=1690204563324~78798',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '2.1 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=131927',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 57,
        minDeliveryTime: 57,
        maxDeliveryTime: 57,
        lastMileTravel: 0,
        lastMileDistance: 2.1,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.1',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '721102',
      name: 'Pista House Tea',
      uuid: '8a4053f6-3841-4c24-b036-61dac8b09661',
      city: '3',
      area: 'Abids & Koti',
      totalRatingsString: '',
      cloudinaryImageId: '0c3e2dd31d5cab7480ab83d9bd600196',
      cuisines: ['Beverages', 'Indian'],
      tags: [],
      costForTwo: 50000,
      costForTwoString: '₹500 FOR TWO',
      deliveryTime: 73,
      minDeliveryTime: 73,
      maxDeliveryTime: 73,
      slaString: '73 MINS',
      lastMileTravel: 0,
      slugs: {
        restaurant: 'pista-house-tea-abids-&-koti-abids-&-koti',
        city: 'Hyderabad',
      },
      cityState: '3',
      address: '',
      locality: 'King Kothi',
      parentId: 236815,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'BASE_DISTANCE',
            fee: 2900,
            message: '',
          },
          {
            name: 'BASE_TIME',
            fee: 0,
            message: '',
          },
          {
            name: 'ANCILLARY_SURGE_FEE',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 2900,
        message: '',
        title: 'Delivery Charge',
        amount: '2900',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.2 kms',
      hasSurge: false,
      cta: {
        link: 'swiggy://menu?restaurant_id=721102',
        type: 'DEEPLINK',
        text: 'RESTAURANT_MENU',
      },
      sla: {
        restaurantId: '',
        deliveryTime: 73,
        minDeliveryTime: 73,
        maxDeliveryTime: 73,
        lastMileTravel: 0,
        lastMileDistance: 1.2,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.4',
      totalRatings: 0,
      new: false,
    },
    subtype: 'basic',
  },
];
